---

- name: Set path to .bashrc
  set_fact:
    bashrc_path: "{{ pyenv_home }}/.bashrc"
  when: bashrc_path is undefined

- name: Check .bashrc file exists
  stat:
    path: "{{ bashrc_path }}"
  register: bashrc_path_stat

- name: Resolve .bashrc symlink
  set_fact:
    bashrc_path: "{{ bashrc_path_stat.stat.lnk_source }}"
  when: bashrc_path_stat.stat.exists and bashrc_path_stat.stat.islnk

- name: Check whether pyenvrc is loaded in the .bashrc file
  command: grep -Fq 'source $HOME/.pyenvrc' {{ bashrc_path }}
  register: check_bashrc
  ignore_errors: True
  changed_when: False
  failed_when: False
  when: bashrc_path_stat.stat.exists

- name: Load pyenvrc in .bashrc
  blockinfile:
    dest: "{{ bashrc_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: pyenv"
    block: |
      if [ -f "$HOME/.pyenvrc" ]; then
        source "$HOME/.pyenvrc"
        source "$HOME/.pyenv/completions/pyenv.bash"
      fi
  when: bashrc_path_stat.stat.exists and check_bashrc.rc != 0
